name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Este flujo de trabajo se ejecutará cuando se haga un push a la rama 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      - name: Build and push Docker image to ACR
        run: |
          docker build -t ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/flask-app:${{ github.sha }} .
          docker push ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/flask-app:${{ github.sha }}
