name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/flask-app:latest \
                       -t ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/flask-app:${{ github.sha }} .
          docker push ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/flask-app:latest
          docker push ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/flask-app:${{ github.sha }}

      - name: Mostrar logs
        run: |
          docker logs $(docker ps -lq)
